-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Projects Table
CREATE TABLE IF NOT EXISTS projects (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_code TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  sector TEXT NOT NULL,
  location TEXT,
  district TEXT,
  state TEXT,
  latitude FLOAT,
  longitude FLOAT,
  progress INT4 DEFAULT 0,
  planned_progress NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'ON TRACK',
  risk_score NUMERIC DEFAULT 0,
  risk_level TEXT DEFAULT 'LOW',
  start_date DATE,
  expected_end_date DATE,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Milestones Table
CREATE TABLE IF NOT EXISTS milestones (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_code TEXT REFERENCES projects(project_code) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  planned_date DATE,
  completed_date DATE,
  status TEXT DEFAULT 'PENDING',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Progress Updates Table
CREATE TABLE IF NOT EXISTS progress_updates (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  project_code TEXT REFERENCES projects(project_code) ON DELETE CASCADE,
  progress INT4 NOT NULL,
  remarks TEXT,
  update_date DATE DEFAULT CURRENT_DATE,
  latitude FLOAT,
  longitude FLOAT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Alerts Table
CREATE TABLE IF NOT EXISTS alerts (
  id INT8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code TEXT REFERENCES projects(project_code) ON DELETE CASCADE,
  severity TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Realtime Configuration
ALTER PUBLICATION supabase_realtime ADD TABLE projects;
ALTER PUBLICATION supabase_realtime ADD TABLE milestones;
ALTER PUBLICATION supabase_realtime ADD TABLE progress_updates;
ALTER PUBLICATION supabase_realtime ADD TABLE alerts;

-- 7. Enable Row Level Security (RLS)
ALTER TABLE projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE milestones ENABLE ROW LEVEL SECURITY;
ALTER TABLE progress_updates ENABLE ROW LEVEL SECURITY;
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;

-- 8. Security Policies
CREATE POLICY "Public Read Access Projects" ON projects FOR SELECT USING (true);
CREATE POLICY "Public Read Access Milestones" ON milestones FOR SELECT USING (true);
CREATE POLICY "Public Read Access Progress" ON progress_updates FOR SELECT USING (true);
CREATE POLICY "Public Read Access Alerts" ON alerts FOR SELECT USING (true);
CREATE POLICY "Allow Public Inserts Progress" ON progress_updates FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow Public Updates Projects" ON projects FOR UPDATE USING (true);